spring.application.name=springboot_server

# create and drop tables
spring.jpa.hibernate.ddl-auto=validate

# Oracle settings
spring.datasource.url=jdbc:oracle:thin:@localhost:1521/orcl21
spring.datasource.username=C##edupath
spring.datasource.password=1234
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.jpa.open-in-view=false
server.port=6767

# application.properties
spring.servlet.multipart.max-file-size=1GB
spring.servlet.multipart.max-request-size=1GB