spring.application.name=springboot_server

# create and drop tables
spring.jpa.hibernate.ddl-auto=validate

# Oracle settings
spring.datasource.url=jdbc:oracle:thin:@localhost:1521/orcl
spring.datasource.username=C##edupath
spring.datasource.password=1902
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.jpa.open-in-view=false
server.port=6767