spring.application.name=springboot_server

# create and drop tables
spring.jpa.hibernate.ddl-auto=validate

# Oracle settings
# Ch?nh s?a orcl thành Service Name ho?c SID c?a USER trong h? qu?n tr? Oracle
spring.datasource.url=jdbc:oracle:thin:@localhost:1521/orcl
# Ch?nh s?a username= username c?a USER trong h? qu?n tr? Oracle
spring.datasource.username=C##EDUPATH
# Ch?nh s?a password thành password c?a USER
spring.datasource.password=1234
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.jpa.open-in-view=false
server.port=6767

# application.properties
spring.servlet.multipart.max-file-size=1GB
spring.servlet.multipart.max-request-size=1GB